# Este arquivo serve como um banco de dados interno para as traduções de segmentos.

DICIONARIO_SEGMENTOS = {
    "accounting": "Contabilidade",
    "airlines/aviation": "Companhias Aéreas/Aviação",
    "alternative dispute resolution": "Resolução Alternativa de Disputas",
    "alternative medicine": "Medicina Alternativa",
    "animation": "Animação",
    "apparel and fashion": "Vestuário e Moda",
    "architecture and planning": "Arquitetura e Planejamento",
    "arts and crafts": "Artes e Artesanato",
    "automotive": "Automotivo",
    "aviation and aerospace": "Aviação e Aeroespacial",
    "banking": "Bancário",
    "biotechnology": "Biotecnologia",
    "broadcast media": "Mídia de Radiodifusão",
    "building materials": "Materiais de Construção",
    "business supplies and equipment": "Suprimentos e Equipamentos para Escritório",
    "capital markets": "Mercado de Capitais",
    "chemicals": "Químicos",
    "civic and social organization": "Organização Cívica e Social",
    "civil engineering": "Engenharia Civil",
    "commercial real estate": "Imobiliário Comercial",
    "computer and network security": "Segurança de Computadores e Redes",
    "computer games": "Jogos de Computador",
    "computer hardware": "Hardware de Computador",
    "computer networking": "Redes de Computadores",
    "computer software": "Software de Computador",
    "construction": "Construção",
    "consumer electronics": "Eletrônicos de Consumo",
    "consumer goods": "Bens de Consumo",
    "consumer services": "Serviços ao Consumidor",
    "cosmetics": "Cosméticos",
    "dairy": "Laticínios",
    "defense and space": "Defesa e Espaço",
    "design": "Design",
    "e-learning": "E-learning",
    "education management": "Gestão Educacional",
    "electrical/electronic manufacturing": "Fabricação Elétrica/Eletrônica",
    "entertainment": "Entretenimento",
    "environmental services": "Serviços Ambientais",
    "events services": "Serviços para Eventos",
    "executive office": "Gabinete Executivo",
    "facilities services": "Serviços de Facilities",
    "farming": "Agricultura",
    "financial services": "Serviços Financeiros",
    "fine art": "Belas Artes",
    "fishery": "Pesca",
    "food and beverages": "Alimentos e Bebidas",
    "food production": "Produção de Alimentos",
    "fund-raising": "Arrecadação de Fundos",
    "furniture": "Mobiliário",
    "gambling and casinos": "Jogos de Azar e Cassinos",
    "glass, ceramics and concrete": "Vidro, Cerâmica e Concreto",
    "government administration": "Administração Governamental",
    "government relations": "Relações Governamentais",
    "graphic design": "Design Gráfico",
    "health, wellness and fitness": "Saúde, Bem-estar e Fitness",
    "higher education": "Ensino Superior",
    "hospital and health care": "Hospitais e Cuidados com a Saúde",
    "hospitality": "Hotelaria",
    "human resources": "Recursos Humanos",
    "import and export": "Importação e Exportação",
    "individual and family services": "Serviços Individuais e Familiares",
    "industrial automation": "Automação Industrial",
    "information services": "Serviços de Informação",
    "information technology and services": "Tecnologia da Informação e Serviços",
    "insurance": "Seguros",
    "international affairs": "Assuntos Internacionais",
    "international trade and development": "Comércio e Desenvolvimento Internacional",
    "internet": "Internet",
    "investment banking": "Banco de Investimento",
    "investment management": "Gestão de Investimentos",
    "judiciary": "Judiciário",
    "law enforcement": "Aplicação da Lei",
    "law practice": "Prática Jurídica",
    "legal services": "Serviços Jurídicos",
    "legislative office": "Gabinete Legislativo",
    "leisure, travel and tourism": "Lazer, Viagens e Turismo",
    "libraries": "Bibliotecas",
    "logistics and supply chain": "Logística e Cadeia de Suprimentos",
    "luxury goods and jewelry": "Artigos de Luxo e Joias",
    "machinery": "Maquinário",
    "management consulting": "Consultoria de Gestão",
    "maritime": "Marítimo",
    "marketing and advertising": "Marketing e Publicidade",
    "market research": "Pesquisa de Mercado",
    "mechanical or industrial engineering": "Engenharia Mecânica ou Industrial",
    "media production": "Produção de Mídia",
    "medical devices": "Dispositivos Médicos",
    "medical practice": "Prática Médica",
    "mental health care": "Cuidados com a Saúde Mental",
    "military": "Militar",
    "mining and metals": "Mineração e Metais",
    "motion pictures and film": "Cinema e Filmes",
    "museums and institutions": "Museus e Instituições",
    "music": "Música",
    "nanotechnology": "Nanotecnologia",
    "newspapers": "Jornais",
    "non-profit organization management": "Gestão de Organizações sem Fins Lucrativos",
    "oil and energy": "Petróleo e Energia",
    "online media": "Mídia Online",
    "outsourcing/offshoring": "Terceirização/Offshoring",
    "package/freight delivery": "Entrega de Pacotes/Cargas",
    "packaging and containers": "Embalagens e Recipientes",
    "paper and forest products": "Papel e Produtos Florestais",
    "performing arts": "Artes Cênicas",
    "pharmaceuticals": "Farmacêuticos",
    "philanthropy": "Filantropia",
    "photography": "Fotografia",
    "plastics": "Plásticos",
    "political organization": "Organização Política",
    "primary/secondary education": "Ensino Fundamental/Médio",
    "printing": "Impressão",
    "professional training and coaching": "Treinamento e Coaching Profissional",
    "program development": "Desenvolvimento de Programas",
    "public policy": "Políticas Públicas",
    "public relations and communications": "Relações Públicas e Comunicação",
    "public safety": "Segurança Pública",
    "publishing": "Publicação",
    "railroad manufacture": "Fabricação Ferroviária",
    "ranching": "Pecuária",
    "real estate": "Imobiliário",
    "recreational facilities and services": "Instalações e Serviços Recreativos",
    "religious institutions": "Instituições Religiosas",
    "renewables and environment": "Energias Renováveis e Meio Ambiente",
    "research": "Pesquisa",
    "restaurants": "Restaurantes",
    "retail": "Varejo",
    "security and investigations": "Segurança e Investigações",
    "semiconductors": "Semicondutores",
    "shipbuilding": "Construção Naval",
    "sporting goods": "Artigos Esportivos",
    "sports": "Esportes",
    "staffing and recruiting": "Recrutamento e Seleção",
    "supermarkets": "Supermercados",
    "telecommunications": "Telecomunicações",
    "textiles": "Têxteis",
    "think tanks": "Think Tanks",
    "tobacco": "Tabaco",
    "translation and localization": "Tradução e Localização",
    "transportation/trucking/railroad": "Transporte/Caminhões/Ferrovias",
    "utilities": "Serviços Públicos",
    "venture capital and private equity": "Capital de Risco e Private Equity",
    "veterinary": "Veterinária",
    "warehousing": "Armazenagem",
    "wholesale": "Atacado",
    "wine and spirits": "Vinhos e Destilados",
    "wireless": "Sem Fio",
    "writing and editing": "Escrita e Edição"
}
